//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EbookPublisherInput
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EbookPublisherInput()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EbookPublisherInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το e-mail του Διαθέτη Δωρεάν Ηλεκτρονικών Βοηθημάτων και Σημειώσεων&lt;br /&gt;[έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string PublisherEmail
        {
            get
            {
                return ResourceManager.GetString("PublisherEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το κινητό τηλέφωνο του Διαθέτη Δωρεάν Ηλεκτρονικών Βοηθημάτων και Σημειώσεων&lt;br /&gt;[πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string PublisherMobilePhone
        {
            get
            {
                return ResourceManager.GetString("PublisherMobilePhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το Ον/μο του Διαθέτη Δωρεάν Ηλεκτρονικών Βοηθημάτων και Σημειώσεων&lt;br /&gt;[ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string PublisherName
        {
            get
            {
                return ResourceManager.GetString("PublisherName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το σταθερό τηλέφωνο του Διαθέτη Δωρεάν Ηλεκτρονικών Βοηθημάτων και Σημειώσεων&lt;br /&gt;[πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string PublisherPhone
        {
            get
            {
                return ResourceManager.GetString("PublisherPhone", resourceCulture);
            }
        }
    }
}
