//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PublicationsOfficeInput
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicationsOfficeInput()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PublicationsOfficeInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το e-mail του Αναπληρωτή Υπευθύνου για το Εύδοξος&lt;br /&gt;[έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string AlternateContactEmail
        {
            get
            {
                return ResourceManager.GetString("AlternateContactEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το κινητό τηλέφωνο του Αναπληρωτή Υπευθύνου για το Εύδοξος&lt;br /&gt;[πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string AlternateContactMobilePhone
        {
            get
            {
                return ResourceManager.GetString("AlternateContactMobilePhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το Ον/μο του Αναπληρωτή Υπευθύνου για το Εύδοξος&lt;br /&gt;[ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string AlternateContactName
        {
            get
            {
                return ResourceManager.GetString("AlternateContactName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το σταθερό τηλέφωνο του Αναπληρωτή Υπευθύνου για το Εύδοξος&lt;br /&gt;[πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string AlternateContactPhone
        {
            get
            {
                return ResourceManager.GetString("AlternateContactPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το e-mail του Υπευθύνου για το Εύδοξος&lt;br /&gt;[έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string ContactEmail
        {
            get
            {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το κινητό τηλέφωνο του Υπευθύνου για το Εύδοξος&lt;br /&gt;[πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string ContactMobilePhone
        {
            get
            {
                return ResourceManager.GetString("ContactMobilePhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το Ον/μο του Υπευθύνου για το Εύδοξος&lt;br /&gt;[ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string ContactName
        {
            get
            {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το σταθερό τηλέφωνο του Υπευθύνου για το Εύδοξος&lt;br /&gt;[πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string ContactPhone
        {
            get
            {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το Ον/μο του Πρύτανη ή του Αντι-Πρύτανη του Ιδρύματος&lt;br /&gt;[ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string DirectorName
        {
            get
            {
                return ResourceManager.GetString("DirectorName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Η Πόλη στην οποία έχει έδρα το Γραφείο Διδακτικών Συγγραμμάτων.
        /// </summary>
        internal static string PublicationsOfficeCity
        {
            get
            {
                return ResourceManager.GetString("PublicationsOfficeCity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το e-mail του Γραφείου Διδακτικών Συγγραμμάτων&lt;br /&gt;[έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string PublicationsOfficeEmail
        {
            get
            {
                return ResourceManager.GetString("PublicationsOfficeEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Το σταθερό τηλέφωνο του Γραφείου Διδακτικών Συγγραμμάτων&lt;br /&gt;[πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string PublicationsOfficePhone
        {
            get
            {
                return ResourceManager.GetString("PublicationsOfficePhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ο Νομός στον οποίο έχει έδρα το Γραφείο Διδακτικών Συγγραμμάτων.
        /// </summary>
        internal static string PublicationsOfficePrefecture
        {
            get
            {
                return ResourceManager.GetString("PublicationsOfficePrefecture", resourceCulture);
            }
        }
    }
}
