using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

namespace Eudoxus.eService
{

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "DistributionPoint")]
    public class DistributionPointDto
    {
        private string distributionPointNameField;

        private string distributionPointOpeningHoursField;

        private string distributionPointPhoneField;

        private string distributionPointMobilePhoneField;

        private string distributionPointFaxField;

        private string distributionPointEmailField;

        private string distributionPointAddressField;

        private string distributionPointZipCodeField;

        private long distributionPointCityIdField;

        private long distributionPointPrefectureIdField;

        private string distributionPointLocationURLField;

        private string contactNameField;

        private string contactPhoneField;

        private string contactMobilePhoneField;

        private string contactEmailField;

        private string usernameField;

        private string passwordField;

        private string passwordSaltField;

        private string emailField;

        private bool isActivatedField;

        private int verificationStatusField;

        private string distributionPointTypeField;

        private long? distributionPointInstitutionIdField;

        private long idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointName
        {
            get
            {
                return this.distributionPointNameField;
            }
            set
            {
                this.distributionPointNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointOpeningHours
        {
            get
            {
                return this.distributionPointOpeningHoursField;
            }
            set
            {
                this.distributionPointOpeningHoursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointPhone
        {
            get
            {
                return this.distributionPointPhoneField;
            }
            set
            {
                this.distributionPointPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointMobilePhone
        {
            get
            {
                return this.distributionPointMobilePhoneField;
            }
            set
            {
                this.distributionPointMobilePhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointFax
        {
            get
            {
                return this.distributionPointFaxField;
            }
            set
            {
                this.distributionPointFaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointEmail
        {
            get
            {
                return this.distributionPointEmailField;
            }
            set
            {
                this.distributionPointEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointAddress
        {
            get
            {
                return this.distributionPointAddressField;
            }
            set
            {
                this.distributionPointAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointZipCode
        {
            get
            {
                return this.distributionPointZipCodeField;
            }
            set
            {
                this.distributionPointZipCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DistributionPointCityID
        {
            get
            {
                return this.distributionPointCityIdField;
            }
            set
            {
                this.distributionPointCityIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DistributionPointPrefectureID
        {
            get
            {
                return this.distributionPointPrefectureIdField;
            }
            set
            {
                this.distributionPointPrefectureIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointLocationURL
        {
            get
            {
                return this.distributionPointLocationURLField;
            }
            set
            {
                this.distributionPointLocationURLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactPhone
        {
            get
            {
                return this.contactPhoneField;
            }
            set
            {
                this.contactPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactMobilePhone
        {
            get
            {
                return this.contactMobilePhoneField;
            }
            set
            {
                this.contactMobilePhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactEmail
        {
            get
            {
                return this.contactEmailField;
            }
            set
            {
                this.contactEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PasswordSalt
        {
            get
            {
                return this.passwordSaltField;
            }
            set
            {
                this.passwordSaltField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsActivated
        {
            get
            {
                return this.isActivatedField;
            }
            set
            {
                this.isActivatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int VerificationStatus
        {
            get
            {
                return this.verificationStatusField;
            }
            set
            {
                this.verificationStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionPointType
        {
            get
            {
                return this.distributionPointTypeField;
            }
            set
            {
                this.distributionPointTypeField = value;
            }
        }

        public bool ShouldSerializeDistributionPointInstitutionID()
        {
            return DistributionPointInstitutionID != null;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long? DistributionPointInstitutionID
        {
            get
            {
                return this.distributionPointInstitutionIdField;
            }
            set
            {
                this.distributionPointInstitutionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

    }
}
