using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

namespace Eudoxus.eService
{

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "Library")]
    public class LibraryDto
    {
        private int institutionIdField;

        private string libraryNameField;

        private string libraryOpeningHoursField;

        private string directorNameField;

        private string libraryPhoneField;

        private string libraryEmailField;

        private string libraryURLField;

        private string libraryAddressField;

        private string libraryZipCodeField;

        private int cityIdField;

        private int prefectureIdField;

        private string libraryLocationURLField;

        private string contactNameField;

        private string contactPhoneField;

        private string contactMobilePhoneField;

        private string contactEmailField;

        private string alternateContactNameField;

        private string alternateContactPhoneField;

        private string alternateContactMobilePhoneField;

        private string alternateContactEmailField;

        private string usernameField;

        private string passwordField;

        private string passwordSaltField;

        private string emailField;

        private bool isActivatedField;

        private int verificationStatusField;

        private long idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int InstitutionId
        {
            get
            {
                return this.institutionIdField;
            }
            set
            {
                this.institutionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryName
        {
            get
            {
                return this.libraryNameField;
            }
            set
            {
                this.libraryNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryOpeningHours
        {
            get
            {
                return this.libraryOpeningHoursField;
            }
            set
            {
                this.libraryOpeningHoursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DirectorName
        {
            get
            {
                return this.directorNameField;
            }
            set
            {
                this.directorNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryPhone
        {
            get
            {
                return this.libraryPhoneField;
            }
            set
            {
                this.libraryPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryEmail
        {
            get
            {
                return this.libraryEmailField;
            }
            set
            {
                this.libraryEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryURL
        {
            get
            {
                return this.libraryURLField;
            }
            set
            {
                this.libraryURLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryAddress
        {
            get
            {
                return this.libraryAddressField;
            }
            set
            {
                this.libraryAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryZipCode
        {
            get
            {
                return this.libraryZipCodeField;
            }
            set
            {
                this.libraryZipCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CityId
        {
            get
            {
                return this.cityIdField;
            }
            set
            {
                this.cityIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PrefectureId
        {
            get
            {
                return this.prefectureIdField;
            }
            set
            {
                this.prefectureIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LibraryLocationURL
        {
            get
            {
                return this.libraryLocationURLField;
            }
            set
            {
                this.libraryLocationURLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactPhone
        {
            get
            {
                return this.contactPhoneField;
            }
            set
            {
                this.contactPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactMobilePhone
        {
            get
            {
                return this.contactMobilePhoneField;
            }
            set
            {
                this.contactMobilePhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactEmail
        {
            get
            {
                return this.contactEmailField;
            }
            set
            {
                this.contactEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlternateContactName
        {
            get
            {
                return this.alternateContactNameField;
            }
            set
            {
                this.alternateContactNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlternateContactPhone
        {
            get
            {
                return this.alternateContactPhoneField;
            }
            set
            {
                this.alternateContactPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlternateContactMobilePhone
        {
            get
            {
                return this.alternateContactMobilePhoneField;
            }
            set
            {
                this.alternateContactMobilePhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlternateContactEmail
        {
            get
            {
                return this.alternateContactEmailField;
            }
            set
            {
                this.alternateContactEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PasswordSalt
        {
            get
            {
                return this.passwordSaltField;
            }
            set
            {
                this.passwordSaltField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsActivated
        {
            get
            {
                return this.isActivatedField;
            }
            set
            {
                this.isActivatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int VerificationStatus
        {
            get
            {
                return this.verificationStatusField;
            }
            set
            {
                this.verificationStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

    }
}
